### ISSUE TITLE
Blue circle, difficult to see what your shot did

### ISSUE THREAD

**Issue by AlexKnauth** [oflatt/space-orbs#21]
Is there a way to make it so that firing a shot doesn't obscure your view of what happens? For instance, there's no way to see, oh, I missed to the left I should adjust to the right for the next shot. Is there a way to fix that?

**Comment by oflatt** [comment]
Normally you should be moving anyways after shooting to see, but that is
still a problem. I don't see a great solution right now.

**Comment by AlexKnauth** [comment]
Would displaying the shots as cones instead of cylinders help?

**Comment by oflatt** [comment]
Turning then into cones still i woukd think does not fix the problem in a nice way. I will look at your code, thanks

**Comment by oflatt** [comment]
I looked into it and I think replacing the cylinder with a cone just makes it super skinny, which has basically the same effect as changing the SHOT-WIDTH variable that I had. I pushed a version with a much skinnier cylinder that I like better. In the future, the width of that cylinder should be something that you can control. I think that just because the cylinder is less thick, it does not make it seem more or less "powerful".
